### ISSUE TITLE
Migrating Argocd to helm

### ISSUE THREAD

**Issue by ilbarone87** [vehagn/homelab#10]
Hi noticed that you've migrated your argocd deployment to helm. This is something I wanted to do it as well and was looking for info on how to do it in the safest way without risking to completely destroy the cluster. Can you share some info please? I imagine you didn't have to redeploy all the apps. Did you just swap kustomize for helm? Were all the applications still there (in the cluster) after the swap or you had to add back again all your applicationset and then wait for Argo to deploy all the apps?
Thanks.

**Comment by vehagn** [comment]
Hi @ilbarone87,

I honestly don't remember if it went well. I've been destroying and recreating the cluster a lot while tinkering. Destroying the cluster has been a non-issue for me as the setup is declarative and I've used hostPath for mounting volumes for the applications that needs storage. The storage is kept intact and I just redeploy the applications.

Sorry if that's not much help.

**Comment by ilbarone87** [comment]
Thank you!
