### ISSUE TITLE
great resource, needs some rework

### ISSUE THREAD

**Issue by Roguito** [vehagn/homelab#5]
try following your instructions in a brand new cluster and you will see where some things that might have grown organically over time in your cluster do not align with your jumpstart instructions which are possibly out of order in regards to assuming CRD's are installed or the secrets-controller having an external-ip.

Learning lots backwards engineering it. Thanks for this resource.

**Comment by jakubauskas** [comment]
> try following your instructions in a brand new cluster and you will see where some things that might have grown organically over time in your cluster do not align with your jumpstart instructions which are possibly out of order in regards to assuming CRD's are installed or the secrets-controller having an external-ip.
> 
> Learning lots backwards engineering it. Thanks for this resource.

Agree, most of the deployment is not working anymore, and needs a complete rework.

**Comment by vehagn** [comment]
@Roguito Thank you for the feedback!

I've been thinking about making the bootstrap process more robust and I admit I haven't been keeping the readme up to date. This issue is just the motivation I need to actually do it!

**Comment by vehagn** [comment]
I've updated the readme. Hopefully it should be easier to get started with a similar configuration now.

**Comment by Roguito** [comment]
It is. Thank you! 

A few more suggestions (especially for the super noobie crowd) mention the base platform being used as your steps refer to xenial which although is not EOL is end of standard support and many tend to gravitate the new and shiny.... also I have not gotten around to checking out the bpf mounts in your steps but for those that don't know how to RTFM for cilium, they may miss that requirement.

**Comment by vehagn** [comment]
@Roguito I'm curious as to why you think I'm using Xenial (Ubuntu 16.04 LTS). I'm using Debian 11 Bullseye which was the new and shiny when I started this project. If you think something is outdated I'd appreciate if you pointed it out so I can fix it.

I haven't done anything custom with BPF mounts for Cilium as the eBPF-integration just works™. Again your comment makes me think I've missed a detail which I'm itching to fix!

**Comment by Roguito** [comment]
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list ;)

I too use straight debian but in my case, bookworm.

I'll say it again, your repo and blog posts have given me much inspiration. Thank you.

**Comment by Roguito** [comment]
In regards to the BPF mounts, luckily debian mounts them automatically but, as an example, unless we followed your blog posts the random github person coming across your repo would not know that your base is debian from the readme.

**Comment by vehagn** [comment]
@Roguito 
> echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list ;)

Ouch, thanks for noticing! That should probably be updated!
I might take some time this weekend to switch over to using Proxmox and update to Bookwork.

> I'll say it again, your repo and blog posts have given me much inspiration. Thank you.

Thanks <3

**Comment by Roguito** [comment]
blog and cloudflare tunnel to the 'eat your own dogfood' infrastructure is down which means you are rebuilding stuff to document your adventure. Can't wait! <3

**Comment by vehagn** [comment]
Haha. That's correct! I'm currently playing around with Proxmox right now.

I didn't think anyone would notice that I switched the blog over to GitLab hosting while I work things out. Which URLs gave it away?

**Comment by Roguito** [comment]
"You've requested a page on a website (stonegarden.dev) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (stonegarden.dev) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it."

You have a Canadian stalker now ;)

**Comment by vehagn** [comment]
Ah! That makes sense. I didn't think anyone would miss that one.

**Comment by Roguito** [comment]
looks like you are going to have your proxmox home lab up before I get my debian/cilium/argo but using vault and external secrets operator but up stealing all your ideas. Keep up the good work mate!

**Comment by vehagn** [comment]
Created a guide on how to get started with [K3s and Cilium](https://blog.stonegarden.dev/articles/2024/02/bootstrapping-k3s-with-cilium/) which I consider to solve this issue.
