### ISSUE TITLE
Needs rework

### ISSUE THREAD

**Issue by jakubauskas** [vehagn/homelab#6]
Seems most of the stuff is outdated, for example Cilium deployment.

root@k8smaster:~/homelab# kubectl kustomize --enable-helm infra/cilium | kubectl apply -f -
namespace/cilium-secrets unchanged
serviceaccount/cilium unchanged
serviceaccount/cilium-operator unchanged
serviceaccount/hubble-relay unchanged
serviceaccount/hubble-ui unchanged
role.rbac.authorization.k8s.io/cilium-gateway-secrets unchanged
role.rbac.authorization.k8s.io/cilium-operator-gateway-secrets unchanged
role.rbac.authorization.k8s.io/cilium-config-agent unchanged
clusterrole.rbac.authorization.k8s.io/cilium unchanged
clusterrole.rbac.authorization.k8s.io/cilium-operator unchanged
clusterrole.rbac.authorization.k8s.io/hubble-ui unchanged
rolebinding.rbac.authorization.k8s.io/cilium-gateway-secrets unchanged
rolebinding.rbac.authorization.k8s.io/cilium-operator-gateway-secrets unchanged
rolebinding.rbac.authorization.k8s.io/cilium-config-agent unchanged
clusterrolebinding.rbac.authorization.k8s.io/cilium unchanged
clusterrolebinding.rbac.authorization.k8s.io/cilium-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/hubble-ui unchanged
configmap/cilium-config unchanged
configmap/configs-dk6k4fbgdg unchanged
configmap/hubble-relay-config unchanged
configmap/hubble-ui-nginx unchanged
secret/cilium-ca configured
secret/hubble-relay-client-certs configured
secret/hubble-server-certs configured
service/hubble-peer unchanged
service/hubble-relay unchanged
service/hubble-ui unchanged
service/traefik-forward-auth unchanged
persistentvolume/cilium-spire-pv unchanged
deployment.apps/cilium-operator configured
deployment.apps/hubble-relay configured
deployment.apps/hubble-ui configured
deployment.apps/traefik-forward-auth configured
daemonset.apps/cilium unchanged
resource mapping not found for name: "traefik-forward-auth-secrets" namespace: "kube-system" from "STDIN": no matches for kind "SealedSecret" in version "bitnami.com/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "default-l2-announcement-policy" namespace: "kube-system" from "STDIN": no matches for kind "CiliumL2AnnouncementPolicy" in version "cilium.io/v2alpha1"
ensure CRDs are installed first
resource mapping not found for name: "default-pool" namespace: "kube-system" from "STDIN": no matches for kind "CiliumLoadBalancerIPPool" in version "cilium.io/v2alpha1"
ensure CRDs are installed first
resource mapping not found for name: "hubble" namespace: "kube-system" from "STDIN": no matches for kind "IngressRoute" in version "traefik.io/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "traefik-forward-auth" namespace: "kube-system" from "STDIN": no matches for kind "Middleware" in version "traefik.io/v1alpha1"
ensure CRDs are installed first

Tried with both 1.28 and 1.29 kube versions

**Comment by vehagn** [comment]
Thanks for the feedback.

I admit I haven't been diligent in updating the readme for a manual bootstrapping of the cluster as things have become interdependent on each other.

The main issue is the tight coupling of in the Cilium folder with Traefik Proxy and Sealed Secrets CRDs.

You could try to apply Sealed Secrets

```shell
kubectl apply -k infra/sealed-secrets
```

and Traefik Proxy

```shell
kubectl kustomize --enable-helm infra/traefik | kubectl apply -f -
```

to install the missing CRDs, though a better fix would be to decouple the Cilium and Hubble config.

You would anyway run into issues decrypting the Sealed Secrets as you (hopefully!) don't have my master-key. I'll have to be more explicit in the readme regarding this.

**Comment by vehagn** [comment]
Closing issue as duplicate of #5
