### ISSUE TITLE
Migration MetalLB to Cilium IPAM

### ISSUE THREAD

**Issue by ilbarone87** [vehagn/homelab#7]
Hello I really enjoyed your 2 guides about Cilium IPAM and gateway api. 
I've tried to follow your tutorial about migration from metallb to cilium but the process didn't go well.
After moving to Cilium the network become quite spotty and was getting a lot of Bad Gateway errors.
Did you just remove metallb IPPool and l2advertsiment and then move to Cilium IPAM to migrate or you had to do other steps?

Thanks

**Comment by vehagn** [comment]
Thank you, I'm glad you liked them.

I removed the MetalLB config in the same commit as as I switched over to Cilium IPAM. You can see the details in [this commit](https://github.com/vehagn/homelab/commit/8d4bb606e47abc89abe124b32c35d3cdce4f176d#diff-b56752406590546208cf3c04974d253ba43d81c5a3a8bbbbb18569f2774a7c93).

**Comment by ilbarone87** [comment]
Ah right. Indeed after I removed completely MetalLB from the cluster it started to work correctly. Quite weird as I removed the IPPool and the L2adv resources for metallb before enabling cilium ipam in my first try and still it was creating issues... Maybe the operator and the speakers for metallb were creating conflicts anyway.
